import PDFDocument from 'pdfkit';
import type { AvaUser } from '@/types';
import type { MemoryLog } from '@/types';

// ─── Colours ──────────────────────────────────────────────────────────────────
const PINK = '#E91E63';
const LIGHT_PINK = '#FCE4EC';
const DARK = '#2D2D2D';
const GREY = '#757575';

export async function generateCycleReport(
  user: AvaUser,
  cycleData: any,
  memoryLogs: MemoryLog[]
): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const buffers: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => buffers.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(buffers)));
    doc.on('error', reject);

    const pageWidth = doc.page.width - 100; // accounting for margins

    // ── Header ────────────────────────────────────────────────────────────────
    doc.rect(0, 0, doc.page.width, 80).fill(PINK);
    doc.fillColor('white').fontSize(24).font('Helvetica-Bold')
      .text('Ava Cycle Report', 50, 25);
    doc.fontSize(11).font('Helvetica')
      .text(`Prepared for ${user.name} · ${new Date().toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' })}`, 50, 52);

    doc.moveDown(3);

    // ── Cycle Overview ────────────────────────────────────────────────────────
    doc.fillColor(PINK).fontSize(14).font('Helvetica-Bold').text('Cycle Overview', 50);
    doc.moveDown(0.5);

    const avg = cycleData?.avg_cycle_length || 28;
    const duration = cycleData?.period_duration || 5;
    const lastPeriodDates = cycleData?.period_start_dates || [];
    const lastPeriod = lastPeriodDates.length
      ? new Date(lastPeriodDates[lastPeriodDates.length - 1])
        .toLocaleDateString('en-NG', { day: 'numeric', month: 'long', year: 'numeric' })
      : 'Not recorded';

    const overviewRows = [
      ['Average cycle length', `${avg} days`],
      ['Typical period duration', `${duration} days`],
      ['Last period start', lastPeriod],
      ['Next period (estimated)', formatDateRange(cycleData?.next_period_start, cycleData?.next_period_end)],
      ['Ovulation window (estimated)', formatDateRange(cycleData?.next_ovulation_start, cycleData?.next_ovulation_end)],
      ['Prediction confidence', `${cycleData?.confidence_pct || 70}%`],
    ];

    drawTable(doc, overviewRows, 50, doc.y, pageWidth);
    doc.moveDown(1.5);

    // ── Symptom Summary ───────────────────────────────────────────────────────
    doc.fillColor(PINK).fontSize(14).font('Helvetica-Bold').text('Symptom Patterns');
    doc.moveDown(0.5);

    const symptoms = memoryLogs.filter(l => ['symptom', 'mood', 'flow'].includes(l.category));
    if (symptoms.length === 0) {
      doc.fillColor(GREY).fontSize(11).font('Helvetica').text('No symptoms logged yet in this period.');
    } else {
      // Count frequency of each symptom keyword
      const freq: Record<string, number> = {};
      symptoms.forEach(s => {
        const key = s.summary.split(':')[0].trim().toLowerCase();
        freq[key] = (freq[key] || 0) + 1;
      });
      const sorted = Object.entries(freq).sort((a, b) => b[1] - a[1]).slice(0, 8);
      const symptomRows = sorted.map(([name, count]) => [
        capitalise(name),
        `${count} time${count > 1 ? 's' : ''}`,
      ]);
      drawTable(doc, symptomRows, 50, doc.y, pageWidth);
    }
    doc.moveDown(1.5);

    // ── Recent Log ────────────────────────────────────────────────────────────
    doc.fillColor(PINK).fontSize(14).font('Helvetica-Bold').text('Recent Activity (Last 30 Days)');
    doc.moveDown(0.5);

    const thirtyDaysAgo = new Date();
    thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

    const recent = memoryLogs
      .filter(l => new Date(l.logged_at) >= thirtyDaysAgo)
      .slice(0, 15);

    if (recent.length === 0) {
      doc.fillColor(GREY).fontSize(11).font('Helvetica').text('No activity in the last 30 days.');
    } else {
      const logRows = recent.map(l => [
        new Date(l.logged_at).toLocaleDateString('en-NG', { day: 'numeric', month: 'short' }),
        capitalise(l.category),
        l.summary,
      ]);
      drawTableWithHeaders(doc, ['Date', 'Type', 'Note'], logRows, 50, doc.y, pageWidth);
    }

    doc.moveDown(2);

    // ── Footer ────────────────────────────────────────────────────────────────
    doc.rect(0, doc.page.height - 50, doc.page.width, 50).fill(LIGHT_PINK);
    doc.fillColor(GREY).fontSize(9).font('Helvetica')
      .text(
        'This report is generated by Ava and is for personal reference only. It does not constitute medical advice. Always consult a qualified healthcare provider for medical concerns.',
        50, doc.page.height - 38, { width: pageWidth, align: 'center' }
      );

    doc.end();
  });
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function formatDateRange(start?: string, end?: string): string {
  if (!start) return 'Not yet calculated';
  const s = new Date(start).toLocaleDateString('en-NG', { day: 'numeric', month: 'short' });
  const e = end ? new Date(end).toLocaleDateString('en-NG', { day: 'numeric', month: 'short' }) : '';
  return e ? `${s} – ${e}` : s;
}

function capitalise(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}

function drawTable(doc: any, rows: string[][], x: number, y: number, width: number) {
  const col1 = width * 0.55;
  const col2 = width * 0.45;
  let cy = y;

  rows.forEach(([label, value], i) => {
    if (i % 2 === 0) {
      doc.rect(x, cy, width, 22).fill('#FFF5F7');
    }
    doc.fillColor(DARK).fontSize(10).font('Helvetica').text(label, x + 8, cy + 6, { width: col1 });
    doc.fillColor(PINK).font('Helvetica-Bold').text(value, x + col1, cy + 6, { width: col2 });
    cy += 22;
  });
  doc.y = cy;
}

function drawTableWithHeaders(doc: any, headers: string[], rows: string[][], x: number, y: number, width: number) {
  const colW = width / headers.length;
  let cy = y;

  // Header row
  doc.rect(x, cy, width, 22).fill(PINK);
  headers.forEach((h, i) => {
    doc.fillColor('white').fontSize(10).font('Helvetica-Bold')
      .text(h, x + i * colW + 6, cy + 6, { width: colW - 6 });
  });
  cy += 22;

  rows.forEach((row, ri) => {
    if (ri % 2 === 0) doc.rect(x, cy, width, 20).fill('#FFF5F7');
    row.forEach((cell, ci) => {
      doc.fillColor(DARK).fontSize(9).font('Helvetica')
        .text(cell, x + ci * colW + 6, cy + 5, { width: colW - 6 });
    });
    cy += 20;
  });
  doc.y = cy;
}
