-- Batch 1 of the symptom/remedy library expansion (target: +150 new
-- conditions total, done in batches). This batch adds 25 new conditions
-- not previously covered by the existing 49, spanning skin, hair, nails,
-- digestive, energy, and musculoskeletal topics. 3 remedies each, matching
-- the density of most existing conditions. One remedy per condition is
-- free, the rest premium, matching the existing free/premium ratio.

INSERT INTO remedies (id, name, condition, condition_label, description, instructions, timing, tracking_note, evidence, caution, premium) VALUES

-- 1. Dark/Discolored Underarms
('lemon_scrub_dark_underarms', 'Lemon & Baking Soda Scrub', 'dark_underarms', 'Dark/Discolored Underarms', 'Alpha hydroxy acids in lemon juice combined with baking soda''s gentle exfoliation can help lighten surface pigmentation over time.', 'Mix 1 tsp baking soda with a few drops of lemon juice into a paste. Apply to clean underarms, leave for 5 minutes, rinse well. Use 2-3 times a week.', 'Any time, ideally after showering.', 'Take a photo every 2 weeks to track gradual lightening.', 'Citric acid is a mild exfoliant that can help fade surface discoloration with consistent use.', 'Can irritate sensitive skin — patch test first, and avoid right after shaving.', false),
('coconut_oil_dark_underarms', 'Coconut Oil Massage', 'dark_underarms', 'Dark/Discolored Underarms', 'Regular oil massage can soften skin texture and reduce friction-related darkening from tight clothing or shaving.', 'Massage a small amount of virgin coconut oil into underarms nightly before bed. Leave on overnight.', 'Nightly, ongoing.', 'Note any change in skin softness after 2 weeks.', 'Coconut oil''s fatty acids support the skin barrier and may reduce irritation-driven pigmentation.', NULL, true),
('deodorant_switch_dark_underarms', 'Switch to a Gentle, Alcohol-Free Deodorant', 'dark_underarms', 'Dark/Discolored Underarms', 'Alcohol and harsh fragrances in some deodorants can irritate underarm skin, worsening discoloration over time.', 'Switch to a fragrance-free, alcohol-free deodorant for at least a month and see if darkening improves.', 'Ongoing.', 'Log which deodorant you switch to and any change after 4 weeks.', 'Reducing chemical irritation is a common first step dermatologists suggest for friction/irritation-related pigmentation.', NULL, true),

-- 2. Dark Inner Thighs & Skin Folds
('loose_clothing_dark_thighs', 'Reduce Friction with Loose Clothing', 'dark_inner_thighs', 'Dark Inner Thighs & Skin Folds', 'Skin-on-skin friction from tight clothing is a common driver of darkening in skin folds.', 'Choose looser-fitting bottoms, especially during exercise or hot weather, to reduce ongoing friction.', 'Ongoing, especially in hot/humid weather.', 'Note if darkening stabilizes or lightens after a few weeks of looser clothing.', 'Reducing mechanical friction is a first-line approach recommended for friction-related skin darkening.', NULL, false),
('sugar_scrub_dark_thighs', 'Gentle Exfoliation with Sugar Scrub', 'dark_inner_thighs', 'Dark Inner Thighs & Skin Folds', 'Regular gentle exfoliation removes dead skin buildup that can make discoloration look more pronounced.', 'Mix 1 tbsp sugar with 1 tbsp coconut oil. Gently massage onto inner thighs in the shower, rinse. Use 2x weekly.', '2x per week.', 'Photograph monthly to track change.', 'Regular exfoliation is commonly suggested to improve the appearance of friction-related hyperpigmentation.', 'Avoid on broken or irritated skin.', true),
('aloe_dark_thighs', 'Aloe Vera Gel Application', 'dark_inner_thighs', 'Dark Inner Thighs & Skin Folds', 'Aloe vera has mild skin-soothing and lightening properties that may help calm irritated, darkened skin.', 'Apply pure aloe vera gel to clean, dry inner thighs nightly. Leave on overnight.', 'Nightly.', 'Track skin tone changes over 4-6 weeks.', 'Compounds in aloe vera have been studied for mild skin-lightening effects.', NULL, true),

-- 3. Ingrown Hairs & Razor Bumps
('warm_compress_ingrown', 'Warm Compress Before Shaving', 'ingrown_hairs', 'Ingrown Hairs & Razor Bumps', 'Warm compresses soften hair and open pores, making hair removal cleaner and reducing the chance of hair curling back into skin.', 'Hold a warm, damp cloth on the area for 2-3 minutes before shaving or waxing.', 'Before every hair removal session.', 'Note if new ingrown hairs reduce over the next 2-3 removal cycles.', 'Softened hair and open follicles are less likely to re-enter the skin after cutting.', NULL, false),
('exfoliate_ingrown', 'Exfoliate Regularly with a Soft Brush', 'ingrown_hairs', 'Ingrown Hairs & Razor Bumps', 'Regular exfoliation prevents dead skin buildup that traps hairs beneath the surface.', 'Gently exfoliate the area with a soft brush or scrub 2-3 times weekly, especially between hair removal sessions.', '2-3x weekly.', 'Log frequency and any reduction in bumps after 3 weeks.', 'Removing dead skin cells is a standard recommendation for preventing ingrown hairs.', 'Skip exfoliating over active, inflamed bumps.', true),
('shave_technique_ingrown', 'Switch Shaving Direction and Technique', 'ingrown_hairs', 'Ingrown Hairs & Razor Bumps', 'Shaving against the grain increases the chance of hair retracting beneath the skin as it grows back.', 'Always shave in the direction of hair growth, use a sharp single-blade razor, and avoid pulling skin taut.', 'Every shave.', 'Note if bumps reduce after switching technique for a month.', 'Shaving with the grain is a widely recommended method to reduce ingrown hair risk.', NULL, true),

-- 4. Dry, Cracked Heels
('overnight_jelly_heels', 'Overnight Petroleum Jelly & Socks', 'cracked_heels', 'Dry, Cracked Heels', 'Sealing in moisture overnight allows deeply dry, cracked skin time to rehydrate and soften.', 'Apply a thick layer of petroleum jelly or a heavy foot cream to clean feet, then wear cotton socks to bed.', 'Nightly until improved, then 2-3x weekly.', 'Track how many nights until cracks visibly soften.', 'Occlusive moisturizers are a standard, effective approach for severely dry skin.', NULL, false),
('foot_soak_heels', 'Weekly Foot Soak & Pumice Scrub', 'cracked_heels', 'Dry, Cracked Heels', 'Soaking softens thickened, callused skin so it can be gently removed rather than continuing to crack.', 'Soak feet in warm water for 15 minutes, then gently use a pumice stone on rough areas. Moisturize immediately after.', 'Weekly.', 'Photograph heels every 2 weeks.', 'Removing built-up callus is commonly recommended alongside moisturizing for cracked heels.', 'Avoid if cracks are deep, bleeding, or infected — see a doctor instead.', true),
('honey_mask_heels', 'Coconut Oil & Honey Mask', 'cracked_heels', 'Dry, Cracked Heels', 'Honey has natural humectant and mild antibacterial properties that can support healing of dry, cracked skin.', 'Mix equal parts coconut oil and honey, apply to heels, cover with socks for 20-30 minutes, then rinse.', '2-3x weekly.', 'Note comfort level and cracking after 2 weeks.', 'Honey''s humectant properties help draw and retain moisture in skin.', NULL, true),

-- 5. Chapped Lips
('honey_overnight_lips', 'Honey Overnight Treatment', 'chapped_lips', 'Chapped Lips', 'Honey''s humectant properties help lips retain moisture overnight, supporting the skin barrier as it heals.', 'Apply a thin layer of raw honey to lips before bed. Leave on overnight (safe to leave, though it may feel sticky).', 'Nightly.', 'Note lip texture improvement over a week.', 'Honey is a natural humectant, commonly used in lip and skin care for hydration.', NULL, false),
('sugar_scrub_lips', 'Gentle Sugar Lip Scrub', 'chapped_lips', 'Chapped Lips', 'Removing dead, flaking skin allows moisturizing products to absorb better and reduces visible peeling.', 'Mix a pinch of sugar with a few drops of honey or olive oil. Gently rub on lips for 30 seconds, then rinse and moisturize.', '1-2x weekly.', 'Track flakiness weekly.', 'Gentle exfoliation is commonly recommended before applying lip balm for better absorption.', 'Avoid if lips are cracked and bleeding — skip exfoliation until healed.', true),
('hydration_lips', 'Stay Ahead of Dehydration', 'chapped_lips', 'Chapped Lips', 'Chronic lip dryness is often a visible sign of overall dehydration, especially during your period when fluid needs can shift.', 'Track your water intake and aim for consistent hydration throughout the day, not just when lips feel dry.', 'Daily, ongoing.', 'Log daily water intake alongside lip condition for 2 weeks.', 'Skin and lip hydration are closely tied to overall body hydration levels.', NULL, true),

-- 6. Dandruff & Flaky Scalp
('acv_rinse_dandruff', 'Diluted Apple Cider Vinegar Rinse', 'dandruff', 'Dandruff & Flaky Scalp', 'The mild acidity of apple cider vinegar may help balance scalp pH and reduce the yeast overgrowth linked to dandruff.', 'Mix 1 part apple cider vinegar with 2 parts water. After shampooing, pour over scalp, massage in, leave 5 minutes, rinse thoroughly.', '1-2x weekly.', 'Track flaking after 3-4 washes.', 'Vinegar''s acidity may help disrupt the fungal environment associated with dandruff.', 'Avoid on broken or irritated scalp skin — can sting.', false),
('tea_tree_dandruff', 'Tea Tree Oil Shampoo Boost', 'dandruff', 'Dandruff & Flaky Scalp', 'Tea tree oil has natural antifungal properties that may target the yeast (Malassezia) commonly linked to dandruff.', 'Add 2-3 drops of tea tree oil to your regular shampoo dose. Massage into scalp, leave 5 minutes, rinse.', 'Every wash.', 'Log flaking and itchiness weekly.', 'Tea tree oil has demonstrated antifungal activity against Malassezia species in studies.', 'Always dilute — never apply undiluted tea tree oil directly to skin.', true),
('clarify_dandruff', 'Reduce Scalp Product Buildup', 'dandruff', 'Dandruff & Flaky Scalp', 'Heavy styling products can build up on the scalp, trapping oil and dead skin and worsening flaking.', 'Use a clarifying shampoo once every 1-2 weeks to fully remove product buildup, then follow with a gentle conditioner.', 'Every 1-2 weeks.', 'Note scalp comfort and flaking after each clarifying wash.', 'Removing buildup is a standard first step recommended for managing dandruff.', NULL, true),

-- 7. Itchy Scalp
('peppermint_itchy_scalp', 'Cooling Peppermint Oil Rinse', 'itchy_scalp', 'Itchy Scalp', 'Peppermint oil has a cooling, mildly numbing effect that can offer quick relief from scalp itchiness.', 'Add 2-3 drops of peppermint oil to a cup of water. Pour over scalp after shampooing, massage gently, rinse.', 'As needed, up to 2-3x weekly.', 'Note itch intensity before and after each use.', 'Menthol in peppermint oil has cooling and mild anti-itch properties.', 'Dilute well — can cause a burning sensation undiluted.', false),
('aloe_itchy_scalp', 'Aloe Vera Scalp Mask', 'itchy_scalp', 'Itchy Scalp', 'Aloe vera''s anti-inflammatory compounds may soothe an irritated, itchy scalp.', 'Apply pure aloe vera gel directly to the scalp, leave for 20-30 minutes, then rinse with a gentle shampoo.', '1-2x weekly.', 'Track itchiness over 2 weeks.', 'Aloe vera has documented anti-inflammatory and soothing effects on irritated skin.', NULL, true),
('gentle_shampoo_itchy_scalp', 'Switch to a Fragrance-Free Shampoo', 'itchy_scalp', 'Itchy Scalp', 'Fragrances and sulfates in some shampoos can irritate a sensitive scalp, contributing to ongoing itchiness.', 'Switch to a sulfate-free, fragrance-free shampoo for at least 3-4 weeks and monitor for improvement.', 'Ongoing.', 'Log which product you switch to and itchiness weekly.', 'Reducing exposure to common irritants is a first-line recommendation for scalp sensitivity.', NULL, true),

-- 8. Dry, Brittle Hair & Split Ends
('hot_oil_split_ends', 'Weekly Hot Oil Treatment', 'split_ends', 'Dry, Brittle Hair & Split Ends', 'Warm oil penetrates the hair shaft better than cold oil, helping restore moisture to dry, brittle strands.', 'Warm coconut or olive oil slightly, apply from mid-length to ends, cover with a warm towel for 20-30 minutes, then shampoo out.', 'Weekly.', 'Note hair softness and breakage weekly.', 'Oils rich in fatty acids can penetrate the hair cortex and reduce protein loss.', NULL, false),
('reduce_heat_split_ends', 'Reduce Heat Styling Frequency', 'split_ends', 'Dry, Brittle Hair & Split Ends', 'Repeated heat exposure is one of the most common causes of split ends and ongoing hair damage.', 'Limit heat styling tools to 1-2x weekly, and always use a heat protectant spray beforehand.', 'Ongoing.', 'Track heat styling frequency and hair condition over a month.', 'Heat damage to the hair cuticle is well documented as a leading cause of split ends.', NULL, true),
('regular_trims_split_ends', 'Regular Trims to Prevent Splitting Upward', 'split_ends', 'Dry, Brittle Hair & Split Ends', 'Split ends don''t heal — they travel further up the hair shaft over time if not trimmed.', 'Trim about a quarter inch off the ends every 8-10 weeks, even while growing your hair out.', 'Every 8-10 weeks.', 'Log trim dates and hair condition between trims.', 'Regular trimming is the only way to remove already-split ends and prevent further splitting.', NULL, true),

-- 9. Brittle, Peeling Nails
('biotin_brittle_nails', 'Biotin-Rich Foods', 'brittle_nails', 'Brittle, Peeling Nails', 'Biotin supports keratin production, the protein that makes up nails, and low intake has been linked to brittle nails.', 'Include more eggs, nuts, seeds, and sweet potatoes in your diet regularly.', 'Ongoing, dietary.', 'Track nail strength monthly — nail growth is slow, so give this 2-3 months.', 'Biotin deficiency has been associated with brittle nail syndrome in studies.', NULL, false),
('cuticle_oil_brittle_nails', 'Cuticle Oil Massage', 'brittle_nails', 'Brittle, Peeling Nails', 'Regular oiling helps prevent moisture loss from nails and surrounding skin, reducing peeling and splitting.', 'Massage a few drops of cuticle oil (jojoba or vitamin E oil work well) into each nail bed nightly.', 'Nightly.', 'Track peeling and splitting weekly.', 'Nail plates lose moisture easily, and regular oiling helps maintain flexibility.', NULL, true),
('limit_water_brittle_nails', 'Limit Water & Chemical Exposure', 'brittle_nails', 'Brittle, Peeling Nails', 'Frequent wetting and drying, along with harsh cleaning products, weakens the nail plate over time.', 'Wear gloves when washing dishes or cleaning, and avoid excessive hand sanitizer use on nails.', 'Ongoing.', 'Log glove use and nail condition over a month.', 'Repeated hydration/dehydration cycles are a well-known cause of nail brittleness.', NULL, true),

-- 10. Nail Ridges
('buffing_nail_ridges', 'Gentle Buffing', 'nail_ridges', 'Nail Ridges', 'Light buffing can smooth the surface appearance of vertical ridges, though it won''t change the ridge itself.', 'Use a fine-grit nail buffer very gently, once every 2 weeks, moving in one direction only.', 'Every 2 weeks.', 'Photograph nails monthly to track appearance.', 'Buffing is a cosmetic approach commonly used to reduce the visible texture of ridges.', 'Over-buffing thins the nail plate — go gently and infrequently.', false),
('moisturize_nail_ridges', 'Moisturize Nail Beds Daily', 'nail_ridges', 'Nail Ridges', 'Dry nail beds can make ridges more pronounced; regular moisturizing supports overall nail plate health.', 'Apply hand cream or nail oil to nail beds daily, massaging gently.', 'Daily.', 'Track nail appearance over 4-6 weeks (nail growth is slow).', 'Well-hydrated nail beds tend to produce a smoother nail plate over time.', NULL, true),
('iron_protein_nail_ridges', 'Check Iron & Protein Intake', 'nail_ridges', 'Nail Ridges', 'Vertical nail ridges are common and often just a normal sign of aging, but they can be worsened by low iron or protein intake.', 'Ensure adequate iron-rich foods (beans, lean meat, leafy greens) and protein in your diet.', 'Ongoing, dietary.', 'Track nail changes over 2-3 months alongside diet.', 'Nail plate formation depends on adequate protein and micronutrient intake.', 'If ridges appear suddenly or are accompanied by discoloration, see a doctor to rule out other causes.', true),

-- 11. Dark Circles Under Eyes
('tea_bags_dark_circles', 'Chilled Tea Bags', 'dark_circles', 'Dark Circles Under Eyes', 'Cold temperature constricts blood vessels under the thin under-eye skin, temporarily reducing the appearance of dark circles.', 'Chill two used tea bags (green or black tea) in the fridge for 15 minutes, then place over closed eyes for 10-15 minutes.', 'As needed, ideally in the morning.', 'Note appearance immediately after and photograph weekly.', 'Cold compresses are a well-known method to reduce under-eye puffiness and vessel visibility.', NULL, false),
('sleep_dark_circles', 'Prioritize Consistent Sleep', 'dark_circles', 'Dark Circles Under Eyes', 'Dark circles are often worsened by poor or inconsistent sleep, which causes blood to pool and skin to appear duller.', 'Aim for a consistent sleep and wake time, even on weekends, for at least 2 weeks.', 'Ongoing.', 'Log sleep hours alongside circle appearance daily.', 'Sleep deprivation is one of the most consistently cited causes of under-eye darkening.', NULL, true),
('cold_spoon_dark_circles', 'Cold Spoon Massage', 'dark_circles', 'Dark Circles Under Eyes', 'Gentle cold massage can improve circulation in the under-eye area and temporarily reduce puffiness that emphasizes shadows.', 'Chill two metal spoons in the freezer for 10 minutes, then gently glide the rounded side under each eye for 1-2 minutes.', 'Morning, as needed.', 'Track puffiness and darkness before/after.', 'Cold therapy constricts blood vessels, reducing visible pooling under thin skin.', NULL, true),

-- 12. Puffy, Swollen Eyes
('reduce_salt_puffy_eyes', 'Reduce Salt Before Bed', 'puffy_eyes', 'Puffy, Swollen Eyes', 'High sodium intake causes fluid retention, which shows up quickly in the thin, delicate skin around the eyes.', 'Avoid salty foods in the evening, especially close to bedtime.', 'Evening, ongoing.', 'Track evening salt intake alongside morning puffiness.', 'Sodium-driven fluid retention is a well-documented cause of facial and under-eye puffiness.', NULL, false),
('elevate_head_puffy_eyes', 'Elevate Your Head While Sleeping', 'puffy_eyes', 'Puffy, Swollen Eyes', 'Fluid pools around the eyes overnight when lying flat; elevation helps it drain rather than settle.', 'Use an extra pillow to slightly elevate your head while sleeping.', 'Nightly.', 'Note puffiness levels each morning over a week.', 'Gravity-assisted drainage is a standard recommendation for reducing morning eye puffiness.', NULL, true),
('cucumber_puffy_eyes', 'Cold Cucumber Slices', 'puffy_eyes', 'Puffy, Swollen Eyes', 'The cooling and mild astringent effect of chilled cucumber can help reduce swelling around the eyes.', 'Place chilled cucumber slices over closed eyes for 10-15 minutes.', 'As needed.', 'Photograph before and after for a few sessions.', 'Cold application constricts blood vessels and reduces fluid buildup in soft tissue.', NULL, true),

-- 13. Acid Reflux & Heartburn
('smaller_meals_reflux', 'Smaller, Slower Meals', 'acid_reflux', 'Acid Reflux & Heartburn', 'Large meals increase stomach pressure, making it easier for acid to travel back up into the esophagus.', 'Eat smaller portions more frequently rather than large meals, and eat slowly.', 'Every meal.', 'Log meal size and reflux symptoms for a week.', 'Reduced stomach distension is a well-established way to lower reflux frequency.', NULL, false),
('avoid_lying_down_reflux', 'Avoid Lying Down After Eating', 'acid_reflux', 'Acid Reflux & Heartburn', 'Gravity helps keep stomach acid down; lying flat soon after eating makes reflux more likely.', 'Wait at least 2-3 hours after eating before lying down.', 'After every meal.', 'Track time between eating and lying down alongside symptoms.', 'Remaining upright after meals is a standard first-line recommendation for reflux management.', NULL, true),
('ginger_tea_reflux', 'Ginger Tea Before Meals', 'acid_reflux', 'Acid Reflux & Heartburn', 'Ginger has been used traditionally to support digestion and may help calm an irritated stomach lining.', 'Drink a cup of mild ginger tea about 20-30 minutes before larger meals.', 'Before meals.', 'Track reflux frequency over 2 weeks.', 'Ginger has documented effects on gastric motility that may reduce reflux symptoms.', 'Very strong ginger can worsen reflux in some people — start mild.', true),

-- 14. Gas & Flatulence
('peppermint_tea_gas', 'Peppermint Tea After Meals', 'gas_flatulence', 'Gas & Flatulence', 'Peppermint relaxes the muscles of the digestive tract, which can help trapped gas move through more easily.', 'Drink a cup of peppermint tea after meals, especially larger or heavier ones.', 'After meals.', 'Track bloating and gas discomfort over a week.', 'Peppermint oil has documented antispasmodic effects on digestive smooth muscle.', 'Can worsen acid reflux in some people — skip if that''s an issue for you.', false),
('chew_slowly_gas', 'Slow Down and Chew Thoroughly', 'gas_flatulence', 'Gas & Flatulence', 'Eating quickly causes you to swallow more air, which contributes directly to gas buildup.', 'Practice chewing each bite 15-20 times and eating without distractions like scrolling your phone.', 'Every meal.', 'Log eating pace and gas symptoms for a week.', 'Swallowed air (aerophagia) is one of the most common, overlooked causes of gas.', NULL, true),
('trigger_foods_gas', 'Identify Trigger Foods', 'gas_flatulence', 'Gas & Flatulence', 'Certain foods (beans, cruciferous vegetables, carbonated drinks) are common gas triggers, and sensitivity varies person to person.', 'Keep a simple food-and-symptom log for 2 weeks to spot patterns in what triggers your gas.', 'Ongoing, 2-week tracking period.', 'This IS the tracking exercise — log meals and gas symptoms daily.', 'Individual food sensitivity is well recognized as a major factor in digestive gas.', NULL, true),

-- 15. Bad Breath
('tongue_scraper_breath', 'Scrape Your Tongue Daily', 'bad_breath', 'Bad Breath', 'Bacteria buildup on the tongue''s surface is one of the most common sources of bad breath, often missed by brushing alone.', 'Use a tongue scraper (or the back of a toothbrush) to gently clean your tongue every morning.', 'Daily, morning routine.', 'Track breath freshness alongside scraping over a week.', 'Tongue coating is a well-documented major contributor to oral malodor.', NULL, false),
('hydration_breath', 'Stay Hydrated Throughout the Day', 'bad_breath', 'Bad Breath', 'A dry mouth reduces saliva, which normally helps wash away odor-causing bacteria.', 'Sip water consistently throughout the day rather than in large amounts occasionally.', 'Ongoing.', 'Track water intake alongside breath freshness.', 'Reduced saliva flow (dry mouth) is directly linked to increased oral bacteria and odor.', NULL, true),
('herbs_breath', 'Chew Fresh Herbs After Meals', 'bad_breath', 'Bad Breath', 'Chlorophyll-rich herbs like parsley and mint have natural deodorizing properties.', 'Chew a small sprig of fresh parsley or mint after meals, especially after garlic or onion-heavy food.', 'After meals.', 'Note breath freshness after use.', 'Chlorophyll has documented mild deodorizing effects in the mouth.', NULL, true),

-- 16. Loss of Appetite
('small_snacks_appetite_loss', 'Small, Frequent Nutrient-Dense Snacks', 'loss_of_appetite', 'Loss of Appetite', 'When a full meal feels overwhelming, smaller frequent portions can help you still meet your nutrition needs.', 'Aim for 5-6 small, nutrient-dense snacks throughout the day instead of 3 large meals.', 'Throughout the day.', 'Track what and how much you''re able to eat daily.', 'Smaller portion sizes are a standard approach recommended when appetite is reduced.', 'If appetite loss is severe or prolonged, please see a doctor — this isn''t something to manage alone long-term.', false),
('walk_before_meals_appetite_loss', 'Add Gentle Movement Before Meals', 'loss_of_appetite', 'Loss of Appetite', 'Light activity can stimulate appetite by supporting healthy digestion and blood flow.', 'Take a short 10-15 minute walk about an hour before a meal you''re struggling to eat.', 'Before meals.', 'Track appetite level before and after short walks.', 'Light exercise has been shown to modestly stimulate appetite in some studies.', NULL, true),
('appealing_meals_appetite_loss', 'Make Meals More Appealing', 'loss_of_appetite', 'Loss of Appetite', 'Appetite is influenced by more than hunger signals — smell, presentation, and variety all play a role.', 'Focus on foods you actually enjoy, vary textures and flavors, and eat in a pleasant, unhurried setting.', 'Every meal.', 'Log which meals felt easier to eat and why.', 'Sensory appeal of food has a measurable effect on appetite and intake.', NULL, true),

-- 17. Increased Appetite / Hunger
('protein_increased_appetite', 'Prioritize Protein at Each Meal', 'increased_appetite', 'Increased Appetite / Hunger', 'Protein is the most satiating macronutrient, helping you feel fuller for longer and reducing constant hunger signals.', 'Include a source of protein (eggs, beans, fish, chicken) at every meal and snack.', 'Every meal.', 'Track hunger levels between meals over a week.', 'Protein has well-documented effects on satiety hormones compared to carbs or fat alone.', NULL, false),
('check_in_increased_appetite', 'Check In Before Reaching for Food', 'increased_appetite', 'Increased Appetite / Hunger', 'Hormonal hunger (especially pre-period) can feel identical to regular hunger, making a brief pause useful.', 'Before eating outside of meal times, pause for a minute and ask if you''re truly hungry or responding to stress, boredom, or habit.', 'As needed, throughout the day.', 'Log what you notice during each pause for a week.', 'Mindful eating pauses are a commonly recommended tool for distinguishing true hunger from other triggers.', NULL, true),
('blood_sugar_increased_appetite', 'Stay Ahead of Blood Sugar Dips', 'increased_appetite', 'Increased Appetite / Hunger', 'Sharp blood sugar drops trigger intense hunger; eating balanced meals helps keep levels steadier.', 'Pair carbohydrates with protein or fat (e.g., fruit with nuts) rather than eating carbs alone.', 'Every meal/snack.', 'Track hunger spikes alongside what you ate beforehand.', 'Balanced macronutrient meals produce a steadier blood glucose response than carbs alone.', NULL, true),

-- 18. Afternoon Energy Crash
('avoid_sugar_lunch_crash', 'Avoid High-Sugar Lunches', 'afternoon_energy_crash', 'Afternoon Energy Crash', 'A sugar or refined-carb-heavy lunch causes a sharp blood sugar spike followed by an equally sharp crash a few hours later.', 'Build lunch around protein, fiber, and healthy fats rather than mostly refined carbs.', 'Lunchtime.', 'Track lunch content alongside afternoon energy for a week.', 'Post-meal blood sugar crashes are a well-documented cause of early-afternoon fatigue.', NULL, false),
('walk_instead_caffeine_crash', 'Short Walk Instead of More Caffeine', 'afternoon_energy_crash', 'Afternoon Energy Crash', 'Light movement increases circulation and alertness without the later crash that comes from another round of caffeine.', 'Take a brisk 10-minute walk when the afternoon slump hits, ideally outdoors.', 'Early-to-mid afternoon.', 'Compare energy after a walk vs. after caffeine on different days.', 'Short bouts of movement have been shown to boost energy and mood comparably to caffeine in some studies.', NULL, true),
('hydration_crash', 'Stay Ahead of Dehydration', 'afternoon_energy_crash', 'Afternoon Energy Crash', 'Even mild dehydration is a common, overlooked cause of the afternoon energy dip.', 'Track your water intake through the morning and aim to be well-hydrated before 2pm.', 'Morning through early afternoon.', 'Log water intake alongside energy levels for a week.', 'Mild dehydration has been linked to fatigue and reduced alertness in studies.', NULL, true),

-- 19. Oversleeping & Grogginess
('consistent_wake_oversleeping', 'Consistent Wake Time, Even on Weekends', 'oversleeping', 'Oversleeping & Grogginess', 'An irregular sleep schedule confuses your body''s internal clock, often making oversleeping feel worse rather than restful.', 'Set the same wake-up time every day, including weekends, even if you go to bed at different times.', 'Daily.', 'Track wake time and grogginess for 2 weeks.', 'Circadian rhythm consistency is one of the most well-supported factors in sleep quality research.', NULL, false),
('morning_light_oversleeping', 'Get Morning Light Exposure', 'oversleeping', 'Oversleeping & Grogginess', 'Natural light exposure shortly after waking helps signal your body to stop producing sleep hormones and feel more alert.', 'Step outside or open your curtains within 30 minutes of waking, for at least 10 minutes.', 'Morning.', 'Track grogginess levels on days you do this vs. don''t.', 'Morning light exposure is well documented to help regulate circadian rhythm and reduce sleep inertia.', NULL, true),
('avoid_snooze_oversleeping', 'Avoid Hitting Snooze Repeatedly', 'oversleeping', 'Oversleeping & Grogginess', 'Falling back into light sleep after an alarm creates new sleep cycles that get interrupted, often worsening grogginess.', 'Place your alarm across the room so you have to get up, rather than repeatedly snoozing.', 'Every morning.', 'Track grogginess on snooze vs. no-snooze mornings.', 'Fragmented sleep from repeated snoozing has been linked to increased sleep inertia.', NULL, true),

-- 20. Neck & Shoulder Tension
('neck_stretches_tension', 'Gentle Neck Stretches', 'neck_shoulder_tension', 'Neck & Shoulder Tension', 'Slow, controlled stretching helps release built-up tension in the neck and upper trapezius muscles.', 'Slowly tilt your head toward each shoulder, holding for 20-30 seconds per side, 2-3 times daily.', '2-3x daily, especially after long periods at a desk.', 'Rate tension before and after stretching.', 'Static stretching is a standard, evidence-supported approach for reducing muscle tension.', 'Move slowly — stop if you feel sharp pain rather than a stretch.', false),
('warm_compress_shoulder_tension', 'Warm Compress on Shoulders', 'neck_shoulder_tension', 'Neck & Shoulder Tension', 'Heat increases blood flow to tense muscles, helping them relax more effectively than stretching alone.', 'Apply a warm towel or heat pack to your neck and shoulders for 15-20 minutes.', 'Evening, or as needed.', 'Track tension levels before/after each session.', 'Heat therapy is well established for relaxing tight skeletal muscle.', NULL, true),
('desk_setup_tension', 'Check Your Desk Setup', 'neck_shoulder_tension', 'Neck & Shoulder Tension', 'Poor posture from screen height or chair position is one of the most common, fixable causes of chronic neck and shoulder tension.', 'Adjust your screen to eye level and ensure your shoulders can relax down, not hunched up, while typing.', 'Ongoing.', 'Log tension levels after adjusting your setup for a week.', 'Ergonomic posture correction is a first-line recommendation for tension-related neck and shoulder pain.', NULL, true),

-- 21. Jaw Clenching & TMJ Tension
('awareness_jaw_clenching', 'Jaw Awareness Check-ins', 'jaw_clenching', 'Jaw Clenching & TMJ Tension', 'Many people clench unconsciously throughout the day, especially during stress, without realizing it.', 'Set a few reminders throughout the day to check your jaw — lips together, teeth apart, tongue resting gently on the roof of your mouth.', 'Several times daily.', 'Log how often you catch yourself clenching.', 'Conscious relaxation techniques are a first-line recommendation for daytime jaw clenching.', NULL, false),
('warm_compress_jaw', 'Warm Compress on the Jaw', 'jaw_clenching', 'Jaw Clenching & TMJ Tension', 'Heat helps relax the tight jaw muscles (masseter) that build tension from clenching or grinding.', 'Hold a warm cloth against your jaw, just in front of your ear, for 10-15 minutes.', 'Evening, or when jaw feels tight.', 'Track jaw soreness before/after.', 'Heat therapy is commonly recommended for muscular jaw tension.', NULL, true),
('jaw_stretches', 'Gentle Jaw Stretches', 'jaw_clenching', 'Jaw Clenching & TMJ Tension', 'Controlled stretching can help release tightness in the jaw muscles and improve range of motion.', 'Slowly open your mouth as wide as comfortable, hold for 5 seconds, then close gently. Repeat 5-10 times.', '1-2x daily.', 'Track jaw comfort over 2 weeks.', 'Jaw stretching exercises are commonly used in TMJ symptom management.', 'If pain is significant, clicking is loud, or jaw locks, see a dentist or doctor.', true),

-- 22. Wrist & Hand Pain
('wrist_stretches_pain', 'Wrist Stretches & Shakes', 'wrist_hand_pain', 'Wrist & Hand Pain', 'Gentle stretching improves circulation and flexibility in the wrist tendons, which can tighten from repetitive use.', 'Extend your arm, gently pull fingers back toward you with the other hand, hold 15-20 seconds. Shake hands out after.', 'Every hour during repetitive tasks (typing, etc.).', 'Track pain levels before/after stretching sessions.', 'Regular stretching breaks are a standard recommendation for repetitive strain-related wrist discomfort.', NULL, false),
('posture_wrist_pain', 'Adjust Your Typing/Phone Posture', 'wrist_hand_pain', 'Wrist & Hand Pain', 'Wrists bent at awkward angles during repetitive tasks put ongoing strain on tendons and nerves.', 'Keep wrists in a neutral, straight position while typing or using your phone — consider a wrist rest if needed.', 'Ongoing.', 'Track pain over a week after adjusting posture.', 'Neutral wrist positioning is a core ergonomic recommendation for preventing repetitive strain injuries.', NULL, true),
('cold_compress_wrist_pain', 'Cold Compress for Acute Soreness', 'wrist_hand_pain', 'Wrist & Hand Pain', 'Cold reduces inflammation and can numb acute discomfort after a flare-up of wrist pain.', 'Apply an ice pack wrapped in a cloth to the wrist for 10-15 minutes.', 'As needed, for acute soreness.', 'Track pain before/after icing.', 'Cold therapy is a standard first response for acute inflammation and pain.', 'Never apply ice directly to skin. If pain is persistent or worsening, see a doctor.', true),

-- 23. Hip Pain
('hip_flexor_stretch', 'Gentle Hip Flexor Stretch', 'hip_pain', 'Hip Pain', 'Tight hip flexors from prolonged sitting are a very common contributor to hip discomfort.', 'Kneel on one knee with the other foot forward, gently push your hips forward until you feel a stretch in the front of the hip. Hold 20-30 seconds each side.', 'Daily, especially if you sit a lot.', 'Track hip discomfort before/after stretching for a week.', 'Hip flexor stretching is a standard recommendation for sitting-related hip tightness.', NULL, false),
('warm_bath_hip_pain', 'Warm Bath or Heat Pad', 'hip_pain', 'Hip Pain', 'Heat increases blood flow and relaxes tight muscles surrounding the hip joint.', 'Soak in a warm bath for 15-20 minutes, or apply a heat pad directly to the hip area.', 'Evening, or as needed.', 'Track pain levels before/after heat application.', 'Heat therapy is well established for relieving musculoskeletal joint discomfort.', NULL, true),
('pillow_knees_hip_pain', 'Sleep With a Pillow Between Your Knees', 'hip_pain', 'Hip Pain', 'Side-sleeping without support can misalign the hips overnight, worsening morning stiffness and pain.', 'If you sleep on your side, place a pillow between your knees to keep hips aligned.', 'Nightly.', 'Track morning hip pain over a week.', 'Hip alignment during sleep is commonly recommended to reduce nighttime joint strain.', 'If pain is sudden, severe, or follows an injury, see a doctor.', true),

-- 24. Tailbone Pain (Coccyx)
('donut_cushion_tailbone', 'Use a Donut or Wedge Cushion', 'tailbone_pain', 'Tailbone Pain (Coccyx)', 'A cushion with a cutout relieves direct pressure on the tailbone while sitting, which is often the main aggravating factor.', 'Use a donut-shaped or wedge cushion when sitting for extended periods, especially on hard surfaces.', 'Whenever sitting for long periods.', 'Track pain levels with and without cushion use.', 'Pressure offloading is a first-line, well-supported approach for coccyx pain.', NULL, false),
('warm_compress_tailbone', 'Warm Compress on the Lower Back/Tailbone', 'tailbone_pain', 'Tailbone Pain (Coccyx)', 'Heat can relax surrounding muscles and ease referred tension around the tailbone area.', 'Apply a warm compress to the lower back and tailbone area for 15-20 minutes.', 'As needed.', 'Track comfort before/after each session.', 'Heat therapy is commonly used to manage musculoskeletal pain in the lower spine region.', NULL, true),
('breaks_sitting_tailbone', 'Avoid Prolonged Sitting Without Breaks', 'tailbone_pain', 'Tailbone Pain (Coccyx)', 'Continuous pressure on the tailbone without relief tends to worsen inflammation and pain over the day.', 'Stand up and move for a few minutes every 30-45 minutes if you sit for work.', 'Throughout the day.', 'Track pain levels on days with regular breaks vs. without.', 'Regular position changes are a standard recommendation for pressure-related tailbone discomfort.', 'If pain follows a fall or injury, or is severe, see a doctor.', true),

-- 25. Rib Pain Around Period
('side_stretches_rib_pain', 'Gentle Side Stretches', 'rib_pain', 'Rib Pain Around Period', 'Hormonal changes can cause mild inflammation around the rib cartilage; gentle stretching may ease associated tightness.', 'Reach one arm overhead and lean gently to the opposite side, holding for 15-20 seconds. Repeat on both sides.', 'Daily, especially during the days rib discomfort occurs.', 'Track rib discomfort before/after stretching.', 'Gentle stretching is commonly used to ease musculoskeletal rib and chest wall tightness.', NULL, false),
('warm_compress_rib_pain', 'Warm Compress on the Rib Area', 'rib_pain', 'Rib Pain Around Period', 'Heat can help relax the intercostal muscles between the ribs, which can tighten with hormonal bloating and shifts.', 'Apply a warm compress to the sides of your rib cage for 15-20 minutes.', 'As needed.', 'Track pain before/after heat use.', 'Heat therapy is a standard approach for musculoskeletal chest wall discomfort.', 'If pain is severe, sudden, or comes with shortness of breath, seek medical care immediately — this could be unrelated to your cycle.', true),
('posture_rib_pain', 'Mind Your Posture While Seated', 'rib_pain', 'Rib Pain Around Period', 'Slouched posture compresses the rib cage and can worsen the sensation of tightness or pain, especially with bloating.', 'Sit upright with shoulders back, allowing your rib cage room to expand fully with each breath.', 'Ongoing, especially while seated for long periods.', 'Track rib comfort on days with more posture awareness.', 'Postural rib cage compression is a recognized contributor to mild rib discomfort.', NULL, true);
