-- Batch 7: final 6 conditions (18 remedies) closing out the library expansion
-- target of ~199 conditions: grey hair, common cold, tired legs and feet,
-- dry nose, sneezing and hoarse voice.

INSERT INTO remedies (id, name, condition, condition_label, description, instructions, timing, tracking_note, evidence, caution, premium) VALUES
('varied_diet_grey_hair', 'Eat a Varied, Nutrient-Rich Diet', 'premature_grey_hair', 'Premature Grey Hair', 'Genes mostly decide when hair greys, but the cells that colour hair need steady nutrition, including protein, iron, copper and B vitamins from food.', 'Include eggs, beans, fish, nuts, seeds, leafy greens and whole grains regularly through the week.', 'Daily, ongoing.', 'Photograph your hairline and parting monthly.', 'Poor nutrition has been linked to earlier greying, though genetics is the biggest factor and these steps may not reverse existing grey.', NULL, false),
('stress_sleep_grey_hair', 'Manage Stress and Protect Your Sleep', 'premature_grey_hair', 'Premature Grey Hair', 'Ongoing stress and poor sleep are linked to faster visible ageing of hair and skin.', 'Build in a daily wind-down, keep a steady sleep schedule and make time for movement you enjoy.', 'Daily.', 'Note stress and sleep quality alongside any hair changes.', 'Research links chronic stress to early greying, though the effect in people is still being studied.', NULL, true),
('avoid_smoke_chemicals_grey_hair', 'Avoid Smoking and Go Easy on Harsh Hair Treatments', 'premature_grey_hair', 'Premature Grey Hair', 'Smoking and repeated bleaching or harsh dyeing can stress the hair and follicles.', 'Avoid smoking, space out bleaching and colouring, and choose gentle shampoos and conditioners.', 'Ongoing.', 'Compare hair condition over a few months.', 'Smoking is associated with earlier greying, and harsh treatments weaken hair.', 'Greying that starts very young, appears suddenly, or comes with tiredness, hair loss or skin changes is worth checking with a doctor.', true),
('rest_fluids_cold', 'Rest and Keep Fluids Up', 'common_cold', 'Common Cold', 'Your body fights a cold best when it is rested and well hydrated, and fluids keep mucus thin.', 'Take it easy, sleep as much as you can and sip water, warm drinks or clear broth through the day.', 'Through the illness.', 'Note how you feel each morning and evening.', 'Rest and fluids are the standard supportive care for colds.', NULL, false),
('warm_soup_honey_cold', 'Warm Soup, Broth or a Honey-Lemon Drink', 'common_cold', 'Common Cold', 'Warm liquids soothe the throat and ease congestion, and honey coats an irritated throat.', 'Sip chicken or vegetable soup, or stir a spoonful of honey and a squeeze of lemon into warm water.', 'Several times daily.', 'Rate throat and chest comfort after each drink.', 'Warm fluids and honey are commonly recommended for cold symptoms.', 'Never give honey to babies under 1 year old.', true),
('steam_saline_cold', 'Steam or a Saline Rinse to Ease Congestion', 'common_cold', 'Common Cold', 'Moist air and salt water thin mucus and help a blocked nose drain.', 'Breathe in steam from a warm shower, or use a saline spray or rinse once or twice a day.', '1-3 times daily.', 'Rate how open your nose feels before and after.', 'Steam and saline are widely used to ease cold-related congestion.', 'Use distilled or boiled-and-cooled water for any rinse. See a doctor if symptoms last more than 10 days, you have a high fever or trouble breathing, or you get worse after starting to improve.', true),
('elevate_legs_tired_legs', 'Raise Your Legs for 10-15 Minutes', 'tired_legs_feet', 'Tired, Aching Legs and Feet', 'Lifting your legs above heart level helps blood and fluid flow back toward the heart and eases heaviness.', 'Lie down and rest your legs up on pillows or against a wall for 10-15 minutes.', 'Once or twice daily, especially after long days on your feet.', 'Rate leg heaviness before and after.', 'Leg elevation is a standard comfort measure for tired, heavy legs.', NULL, false),
('warm_soak_tired_legs', 'Warm Foot Soak With Gentle Massage', 'tired_legs_feet', 'Tired, Aching Legs and Feet', 'Warmth relaxes tight muscles and a gentle massage boosts circulation.', 'Soak your feet in comfortably warm water for 15 minutes, then massage feet and calves with slow upward strokes.', 'Evenings as needed.', 'Note how your feet feel the next morning.', 'Warm soaks and massage are commonly used to relieve tired feet and legs.', NULL, true),
('move_footwear_tired_legs', 'Move Often and Wear Supportive Footwear', 'tired_legs_feet', 'Tired, Aching Legs and Feet', 'Standing or sitting still for long stretches and unsupportive shoes make legs ache more.', 'Change position every 30-60 minutes, do gentle calf stretches, and wear supportive, well-fitting shoes.', 'Through the day.', 'Track which activities or shoes make aching worse.', 'Regular movement and supportive footwear reduce strain on legs and feet.', 'Swelling, redness, warmth or pain in one calf, or aching with numbness or tingling, needs prompt medical attention.', true),
('saline_spray_dry_nose', 'Saline Spray or Rinse', 'dry_nose', 'Dry Nose', 'Salt water moisturizes the inside of the nose and loosens dried crusts.', 'Use a saline nasal spray or gentle rinse once or twice a day.', '1-2 times daily.', 'Note dryness and crusting each morning.', 'Saline is a standard first step for a dry or crusty nose.', 'Use distilled or boiled-and-cooled water for any rinse, never straight tap water.', false),
('humidify_dry_nose', 'Add Moisture to the Air', 'dry_nose', 'Dry Nose', 'Dry indoor air, especially overnight, is a leading cause of a dry nose.', 'Run a humidifier in the bedroom, or breathe in steam from a warm shower.', 'Nightly, plus steamy showers as needed.', 'Compare how your nose feels on waking.', 'Humidified air helps keep nasal passages moist.', NULL, true),
('gentle_care_dry_nose', 'Use a Tiny Dab of Petroleum Jelly and Do Not Pick', 'dry_nose', 'Dry Nose', 'A thin barrier at the nostril opening locks in moisture, and picking makes dryness and bleeding worse.', 'Dab a very small amount of petroleum jelly just at the nostril opening, not deep inside, and avoid picking or blowing hard.', 'Once or twice daily, such as at bedtime.', 'Note crusting and any bleeding.', 'Gentle barrier care and not picking protect dry nasal skin.', 'Frequent nosebleeds, crusting that does not improve, or a nose that stays blocked on one side need a doctor.', true),
('find_triggers_sneezing', 'Spot and Avoid Your Triggers', 'sneezing', 'Frequent Sneezing', 'Dust, pollen, smoke, strong scents and pet dander commonly set off sneezing fits.', 'Note when sneezing happens and what is around, then cut back on the likely triggers, such as scented products or smoky rooms.', 'Ongoing.', 'Keep a short log of times, places and triggers for 1-2 weeks.', 'Identifying and avoiding triggers is the foundation of managing sneezing.', NULL, false),
('rinse_wash_up_sneezing', 'Rinse Your Nose and Wash Up After Being Outside', 'sneezing', 'Frequent Sneezing', 'Rinsing clears irritants out of the nose, and washing removes pollen from skin and hair.', 'Use a saline spray or rinse, shower and rinse your hair in the evening, and change clothes after being outdoors.', 'Daily during bad spells.', 'Compare how often you sneeze on days you do this.', 'Saline rinsing and washing off pollen are commonly recommended for allergen-related sneezing.', 'Use distilled or boiled-and-cooled water for any rinse.', true),
('dust_down_sneezing', 'Cut Down on Dust at Home', 'sneezing', 'Frequent Sneezing', 'Dust and mites in bedding and soft furnishings are very common sneeze triggers.', 'Wash bedding weekly in hot water, damp-dust surfaces rather than dry-dusting, and vacuum regularly.', 'Weekly.', 'Note whether morning sneezing improves.', 'Reducing household dust lowers exposure to common indoor allergens.', 'Sneezing with wheezing, shortness of breath or fever, or lasting several weeks, should be checked by a doctor.', true),
('voice_rest_hoarse', 'Rest Your Voice', 'hoarse_voice', 'Hoarse Voice', 'Straining a hoarse voice irritates the vocal cords further and slows recovery.', 'Talk as little as you can, avoid shouting, whispering and constant throat clearing, and sip water instead.', 'Until your voice recovers.', 'Note how your voice sounds each morning.', 'Voice rest is the standard first step for a hoarse voice.', NULL, false),
('warm_fluids_steam_hoarse', 'Warm Fluids and Steam', 'hoarse_voice', 'Hoarse Voice', 'Moisture keeps the vocal cords supple and soothes irritation.', 'Sip warm water or herbal tea through the day and breathe in steam from a warm shower.', 'Several times daily.', 'Rate how smooth your voice feels afterwards.', 'Hydration and humidified air are commonly recommended for hoarseness.', NULL, true),
('avoid_irritants_hoarse', 'Avoid Smoke, Alcohol and Very Dry Air', 'hoarse_voice', 'Hoarse Voice', 'These dry out and inflame the vocal cords.', 'Stay away from smoke and alcohol while hoarse, and use a humidifier in dry rooms.', 'Until your voice recovers.', 'Note which situations make your voice worse.', 'Smoke, alcohol and dry air are known irritants of the throat and vocal cords.', 'Hoarseness lasting more than 2-3 weeks, or with trouble swallowing or breathing, coughing up blood, or after an injury, needs a doctor, especially if you smoke.', true);
